jira:
  host: ${JIRA_HOST}
  api:
    standard: /rest/api/2
    agile: /rest/agile/1.0
    insight: /rest/insight/1.0
  auth:
    username: ${JIRA_USERNAME}
    password: ${JIRA_PASSWORD}
  timezone: ${JIRA_TIMEZONE}

logging.level.com.basgeekball.jirasteward.client: DEBUG
