jira:
  host: ${JIRA_HOST}
  api:
    common: /rest/api/2
    insight: /rest/insight/1.0
  auth:
    username: ${JIRA_USERNAME}
    password: ${JIRA_PASSWORD}

logging.level.com.basgeekball.jirasteward.client: DEBUG
